# Generated by Django 4.2.9 on 2024-01-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=24)),
                ("lastname", models.CharField(max_length=24)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
