# Generated by Django 4.2.9 on 2024-01-11 09:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("create_user", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="MyUser",
        ),
    ]
